// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdukvpwatoktucrzeqxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdWt2cHdhdG9rdHVjcnplcXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMjU4OTIsImV4cCI6MjA4ODYwMTg5Mn0.4x2FFfQ-YrB0RMYaE_8iNqtkRu0jFwrpK1G5Lk-LhUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: import.meta.env.PROD, // Solo persiste en producción
    autoRefreshToken: true,
  }
});